export enum languageKeys {
  "HEADER_HOME",
  "HEADER_SUPPORT",
  "HEADER_PREGNANCY_TOOLS",
  "HEADER_OVULATION_CALCULATOR",
  "HEADER_BLOG",
  "HEADER_ABOUT_US",
  "HEADER_DOWNLOAD",
  "APP_NAME",
  "APP_SUBTITLE",
  "APP_DESCRIPTION",
}
